### ISSUE TITLE
[Mega-thread] New/Upcoming Services

### ISSUE THREAD

**Issue by kvangent** [PokeAlarm/PokeAlarm#147]
# In order to consolidate Issues, all matters regarding new or unsupported services should be posted here.

Reset as of 11/04/2017

If you would like to see a new service, please make a post below with a link to the API of the service you wish to use.

**Under Investigation**

**In Progress**

**Completed**

**Not in Progress**

**Comment by KongGal** [comment]
Maybe IRC? its old but still used by a lot and should be easy to work with

**Comment by tylerdola** [comment]
What about WhatsApp like this project? https://github.com/akleemans/pokenotifier-whatsapp

**Comment by Albert62** [comment]
I think it would be a great idea to have an App (Android, iOS) so you could receive notifications.

**Comment by kvangent** [comment]
@Albert62 All of these services work on Android and iOS.

**Comment by Albert62** [comment]
@kvangent yeah I know, I've been using Telegram. I was thinking of a standalone app, not using any of this services so you could get the notifications.

**Comment by brettgus** [comment]
@tylerdola Whatsapp is known to ban phone numbers that use bots, from what I've read.  So that probably isn't a good fit

**Comment by tylerdola** [comment]
I was just coming on here to say that my number has been banned now for using the automated yowsup code. Not a good idea!

**Comment by kbtbc** [comment]
Google Hangouts 
(This is not a personal request, but I saw it asked in the pogom discord channel:)
Python API: https://github.com/tdryer/hangups

**Comment by brettgus** [comment]
@kbtbc That API is not going work for us.  It requires Python >=3.3, PokeAlarm (like PokemonGo-Map) uses Python 2.7

**Comment by nicktan147** [comment]
Any chance of supporting OnePush notification push?

https://onesignal.com/

**Comment by kbtbc** [comment]
Pardon for the very base level request, but how about just send email?

(the reason I ask is because I was using Twilio and quickly reached the 'trial' limit for SMS, and most providers have an email that automatically converts to SMS  (ie. 2125555555@provider.com)

**Comment by jakeb16** [comment]
I was also thinking it would be nice to support email. My twilio account is also loosing its trial

**Comment by bluelatios** [comment]
Pardon me, can PokeAlarm send notification based on location request from telegram?
Like @hotorbot bot on telegram

**Comment by RADiEnCe** [comment]
Hi. I want to help develop a bot for GroupMe. I have a very basic working version right now. Where do I find documentation to make it comply to the standards of this project? Ps I am a Gitgub NOOB

**Comment by kaitoxakimoto** [comment]
it would be nice if the argument of the geofence could be in alarms.json
why?
for example, one could send multiple telegrams for many areas with just one process, and not copy-paste many alarms :/
in my case, with pokemon go map, i scan the area of all my city, and send it to 8 telegram channel, and i have to open then, 8 processes with 8 alarms and 8 geofences :/ 

sry for my english, im chilean :C

**Comment by Dracon23** [comment]
[Join](https://joaoapps.com/join/) - [AutoRemote](https://joaoapps.com/autoremote/)

both offer sending messages via URL, so integrating them should not require a large API.

**Comment by danwie** [comment]
I suggest "max_dist":"1000" for gyms.

**Comment by m4rtint** [comment]
Is it possible at this moment to add notification that a gym reached level 10?

**Comment by lukemcinerney** [comment]
Possible to add GroupMe support?

**Comment by ExiledSenpai** [comment]
I would like GroupMe support.

**Comment by lukemcinerney** [comment]
https://dev.groupme.com/

**Comment by artysta123** [comment]
Hello 
I have modem gsm plugged into usb and i have idea, it is possible to add option for external command on linux box to send notification?
For example in config add:
 1. command ( /usr/sbin/sendsms.sh) 
 2. phone numer ( +48 123 456 789) 
 3. Format messeage ( <pkmn> has appear... date .. etc etc... )

**Comment by goliom** [comment]
Is it possible to add whatsapp post ?

**Comment by rboss726** [comment]
I would like to have band.us added, its very simple and the api is here : https://openapi.band.us/v2.2/band/post/create

**Comment by FrankWouda** [comment]
Is it possible to have the discord posts be removed after the pokemon/raid is not active anymore?

**Comment by trunksbomb** [comment]
GroupMe
https://dev.groupme.com/docs/v3

**Comment by Dracon23** [comment]
As has been requested before: **Join**
[API Docs](https://joaoapps.com/join/api/)

Join would be interesting as I can interact from it with Tasker and thus react from my device itself.

**Comment by kvangent** [comment]
Flock Messenger - [docs](https://docs.flock.com/)

Suggested by @nmilitello

**Comment by kvangent** [comment]
Closing - we don't get as many requests for different services as we used too, and having them all in one issue is preventing people from seeing and participating in requests. If you are still interested in getting support for a new service, please open a new issue and we will track progress there.
