### ISSUE TITLE
[Mega-thread] Language Support

### ISSUE THREAD

**Issue by kvangent** [PokeAlarm/PokeAlarm#293]
# In order to consolidate Issues, this thread will be used to track locales. If you wish to see your language included, please request it below. 

With v3, a number of locales were dropped because of lack of community support. 

If you wish to see your language supported, please comment below. 

**Currently Supported**
en
de
fr
it
es

**Requested**

**Comment by Faileador** [comment]
es - spanish

Pokemon names are the same, moves and teams not.

**Comment by kvangent** [comment]
@Faileador ES has been added.

**Comment by MARTINI1** [comment]
I arrived late, had translated all to Spanish, but I have not created the pr (noob in git xD).
Even so, i've created pr because they have not been translated correctly. #295

**Comment by fantasy4u** [comment]
Address could it be support Hong Kong, Traditional Chinese ..

**Comment by rakuuhwa** [comment]
hu - hungarian (names and teams are the same, just move-s are different.

**Comment by kvangent** [comment]
Closing this thread - requests for supported languages don't occur as often as they did when we created this issue. If you are interested in requesting support for a new language, please feel free to open a new issue.
