### ISSUE TITLE
[Enhancement] Better handling and monitoring of child processes. 

### ISSUE THREAD

**Issue by evilmoses** [PokeAlarm/PokeAlarm#309]
## Enhancement Description
Have PA handle child processes better, and be able to tell if one has died so it can be restarted. 

## Suggested fix
Reworked managers to have some basic health checks, give server ability to restart mangers that do not check in.

**Comment by kvangent** [comment]
I am not opposed to this, but I think a better way would be to just count how long it has been since a webhook has been delivered and generate a message based on that.

**Comment by kvangent** [comment]
#465 Partially addresses this by adding in gracefully shutdown for child processes.

**Comment by kvangent** [comment]
This is no longer an issue because multiprocessing was removed in 1e69365cd98d359ebbaaa1f712afb97ce6a7dde1, so child process can no longer get hung up.
