### ISSUE TITLE
[ENHANCEMENT] Add the nearest train/subway station (code included)

### ISSUE THREAD

**Issue by eike42** [PokeAlarm/PokeAlarm#370]
!--- [ENHANCEMENT] Use this template if you have a suggestion for improving PokeAlarm   -----
## Enhancement Description
!--- Please describe the improvement you are proposing.  --
Add the nearest train station (name and distance) to to the pokealarm notification.
## Use cases
!--- Please describe why you think this improvement will be useful --
Cars stink and in some cities it is still too cold to cycle.  It would be great to have the option to show the nearest train station. This can be easily done using google maps API, I have included the python function to add to Manager.py. Unfortulately I do not have a working PokeAlarm myself so I cannot make a pull request, but adding this to the tool should be pretty straightforward. 
[PokeAlarm_Manager_py_addition.txt](https://github.com/PokeAlarm/PokeAlarm/files/928094/PokeAlarm_Manager_py_addition.txt)
Thanks for the great work.
Eike
## Other Links
!--- If you are suggesting a new service, please include a link to relevant API or Python module --

!--- END OF [ENHANCEMENT] TEMPLATE  ---------------------------------------------------------------

**Comment by kvangent** [comment]
Closing - this is an older issue without a lot of requests or feedback. If you feel strongly that this issue would be valuable in PA, please open a new issue.
