### ISSUE TITLE
[FacebookPages] Missing images, description, and other functionality 

### ISSUE THREAD

**Issue by Toetje585** [pokealarm/pokealarm#413]
## Problem Description
Pokemon images and raid description missing on Facebook posts.

See: https://www.facebook.com/Pok%C3%A9Pok%C3%A9-Maastricht-1896224483963520/

## Problem Origin
Facebook has updated their API and removed functionality that PA originally used. 

## Problem Solution
The FacebookPages alarm needs to to be updated to reflect the change in functionality.

**Comment by Toetje585** [comment]
Forgot google maps static key....

**Comment by kvangent** [comment]
According to the [facebook sdk changelog] (http://facebook-sdk.readthedocs.io/en/latest/changes.html?highlight=put_wall_post) it looks like push_wall_post is deprecated and put_object is the new endpoint. This endpoint doesn't seem to have image or caption parameters, so we may be unable to customize these anymore. I will need to look into it.

**Comment by darkelement1987** [comment]
Having the same problem, did you manage to solve it perhaps?

**Comment by LegitDongo** [comment]
@Toetje585 @darkelement1987 
How long ago did you set up FB integration?
Did you go through an approval process for your app?
