### ISSUE TITLE
[ENHANCEMENT] Filter raids by level

### ISSUE THREAD

**Issue by JoseLSegura** [PokeAlarm/PokeAlarm#415]
## Filter raids by level

Equals to eggs filters, it is interesting filtering raids by level instead only by Pokemon.

I propose to add in the default part of raids configuration, and can be overwriten by a Pokemon specific config

## Use cases
This will be very useful to helping newbies, because it is a common problem to configure raids and get no notifications because you didn't configure any Pokemon, so any raid is notified.

This will help to simplify the filters.json file, because you can avoid most of the Pokemon specific lines. For example, notify only the level 5 raids AND Tyranitar, Snorlax and Lapras.

Thank you

**Comment by darkelement1987** [comment]
Just use

>       },
        "Articuno":"True",
        "Zapdos":"True",
        "Moltres":"True",
        "Mewtwo":"True",
        "Mew":"True",
        "Raikou":"True",
        "Entei":"True",
        "Suicune":"True",
        "Lugia":"True",
        "Ho-Oh":"True",
            }

**Comment by smbambling** [comment]
👍

**Comment by na-ji** [comment]
Would be really cool. Because separating pokemons by level is really a pain. Even more when Niantic adds new raids.
