### ISSUE TITLE
[BUG] Big Magikarp weight threshold is wrong

### ISSUE THREAD

**Issue by dsorc** [PokeAlarm/PokeAlarm#429]
## Problem Description
Some Magikarp with 13.13kg weight or more are not reported as big by pokealarm.

I don't know if the weight threshold is in the webhook (so rocketmap issue) or in pokealarm.
Meaning I also don't know if the threshold is computed or is a constant number.

Threshold info:
https://www.reddit.com/r/TheSilphRoad/comments/5nuipx/fisherman_medal_weights/

## Your Environment
not relevant

## Console Output
not relevant

## Your Alarms Config
not relevant

## Troubleshooting Checklist
[x] Most recent version of RocketMap
[x] Most recent version of PokeAlarm
[x] Checked the Wiki page for service in question

**Comment by kvangent** [comment]
The way the post reads, it doesn't seem clear that the cutoff is 13.13kg. Is there any more data to support this claim?

**Comment by dsorc** [comment]
I know I caught quite a few big Magikarp that were not reported by PokeAlarm and they counted toward the achievement since they were over 13.13kg. I also caught some with less than 13.13 and they didn't count. My limited experience matches with the data in the thread.

The lightest I've seen on twitter notifications is 12.9kg, which is clearly too light.
https://twitter.com/KarpadorTM/status/850390381074284545

Would be nice to at least check if the current threshold is a constant or a function. If it's a function it should be checked as it might incorrectly be taking the height into consideration.

**Comment by kvangent** [comment]
There is a calculation involved - when it was introduced there was another silph post detailing the math behind it.

I have no issues with someone submitting a PR to change the function to a simple check for weight if there is evidence to suggest that is the threshold.

**Comment by LegitDongo** [comment]
The research in the Silph Road post looks like the best and most relevant one.
Likewise, I've found these for the tiny Ratatta related fix.
https://www.reddit.com/r/TheSilphRoad/comments/5931wy/youngster_medal_you/
https://www.reddit.com/r/TheSilphRoad/comments/6kf124/youngster_medal_tiny_rattata_exact_size/
https://www.reddit.com/r/TheSilphRoad/comments/55xq49/how_size_is_determined_in_pokemon_go_plus/

**Comment by kvangent** [comment]
commit ed13fc0e87beb7be399a8d6bb29c7fd34f096eaa
