### ISSUE TITLE
[BUG] Time stamp inconsistency

### ISSUE THREAD

**Issue by boby361** [PokeAlarm/PokeAlarm#434]
## Problem Description
In command prompt the time stamps become broken. the number 2 from 2017 will be often cut from a bunch of time stamps and put into other timestamps. 

## Your Environment
Has always happened. Previously in Win7 and now in WinServ 2008
Python Version: 2.7.1
PokeAlarm startup command `python ./start_pokealarm.py`

Did the issue persist after restarting the script (yes)
always there.

## Console Output
222222017-09-27 01:58:16,960 [manager1][   Manager][    INFO] Omanyte rejected: CP information was missing - (F #0)
017-09-27 01:58:16,961 [manager2][   Manager][    INFO] Omanyte rejected: CP information was missing - (F #0)
017-09-27 01:58:16,961 [manager3][   Manager][    INFO] Omanyte rejected: CP information was missing - (F #0)
017-09-27 01:58:16,961 [manager4][   Manager][    INFO] Omanyte rejected: CP information was missing - (F #0)
017-09-27 01:58:16,963 [manager5][   Manager][    INFO] Omanyte rejected: CP information was missing - (F #0)
017-09-27 01:58:16,963 [manager6][   Manager][    INFO] Omanyte rejected: CP information was missing - (F #0)
2017-09-27 01:58:17,813 [manager1][   Manager][    INFO] Crobat ignored: no filters are set
2017-09-27 01:58:17,815 [manager2][   Manager][    INFO] Crobat ignored: no filters are set
2017-09-27 01:58:17,815 [manager3[   Manager][    INFO] Crobat ignored: no filters are set
22222017-09-27 01:58:17,818 [manager4][   Manager][    INFO] Crobat ignored: no filters are set
22017-09-27 01:58:17,818 [manager5][   Manager][    INFO] Crobat ignored: no filters are set
017-09-27 01:58:17,818 [manager6][   Manager][    INFO] Crobat ignored: no filters are set
017-09-27 01:58:17,818 [manager1][   Manager][    INFO] Crobat ignored: no filters are set
017-09-27 01:58:17,816 [manager2][   Manager][    INFO] Crobat ignored: no filters are set
22222017-09-27 01:58:17,818 [manager3][   Manager][    INFO] Crobat ignored: no filters are set
017-09-27 01:58:17,819 [manager4][   Manager][    INFO] Crobat ignored: no filters are set
017-09-27 01:58:17,815 [manager5][   Manager][    INFO] Crobat ignored: no filters are set
017-09-27 01:58:17,816 [manager6][   Manager][    INFO] Crobat ignored: no filters are set
## Your Alarms Config

(its a wee bit old although iv had this issue from the beginning. before things were removed)
[
  {
    "active": "False",
    "type": "boxcar",
    "user_credentials": "YOUR_API_KEY"
  },
  {
    "active": "True",
    "type": "discord",
    "startup_message": "False",
    "webhook_url": "https://discordapp.com/api/web",
    "pokemon":{
    "username": "<pkmn> <iv>% <cp> #<pkmn_id>",
    "webhook_url": "https://discordapp.com/api/web",
    "icon_url": "https://raw.githubusercontent.com/kvangent/PokeAlarm/master/icons/<pkmn_id>.png",
    "title": "Click Here to find the <pkmn>",
    "url": "<gmaps>",
    "body": "-IV%: <iv> (<atk>,<def>,<sta>) \n -CP: <cp> \n -Move1: <quick_move> \n -Move2: <charge_move> \n -Available until <12h_time> (<time_left>).",
	"map": {
    "enabled": "True",
	"zoom": "14"
      }
 },
    "pokestop":{
    "username":"Lured Pokestop",
    "webhook_url":"https://discordapp.com/api/web",
    "icon_url" : "https://raw.githubusercontent.com/kvangent/PokeAlarm/master/icons/pokestop.png",
    "title": "Lured Stop around: [<neighborhood>] <address>",
    "url": "<gmaps>",
    "body": "expires at <12h_time> (<time_left>)."
    },
    "raid": {
    "username": "<pkmn> Raid",
    "webhook_url":"https://discordapp.com/api/we",
    "content": "",
    "icon_url": "https://raw.githubusercontent.com/kvangent/PokeAlarm/master/icons/<pkmn_id>.png",
    "avatar_url": "<gym_url>",
    "title": "Click Here to find the <pkmn> Raid!",
    "url": "<gmaps>",
    "body": " At Gym: <gym_name> \nAround: <neighborhood>  \nThe raid is available until <12h_time> (<time_left>).",
	"map": {
    "enabled": "True",
	"zoom": "14"
      }
        },
    "egg": {
    "username": "Lv <raid_level> Raid Egg!",
    "webhook_url":"https://discordapp.com/api/webh",
    "content": "",
    "icon_url": "https://raw.githubusercontent.com/kvangent/PokeAlarm/master/icons/egg_<raid_level>.png",
    "avatar_url": "<gym_url>",
    "title": "Click Here to find the Lv <raid_level> Raid!",
    "url": "<gmaps>",
    "body": " At Gym: <gym_name> \nAround: <neighborhood> \nIt will hatch at <begin_12h_time> (<begin_time_left>).",
	"map": {
    "enabled": "True",
    "zoom": "14"
      }
        }
  },
  {
    "active": "False",
    "type": "facebook_page",
    "page_access_token": "YOUR_PAGE_ACCESS_TOKEN"
  },
  {
    "active": "False",
    "type": "pushbullet",
    "api_key": "YOUR_API_KEY"
  },
  {
    "active": "False",
    "type": "pushover",
    "app_token": "YOUR_APP_TOKEN",
    "user_key": "YOUR_USER_KEY"
  },
  {
    "active": "False",
    "type": "slack",
    "api_key": "YOUR_API_KEY"
  },
  {
    "active": "False",
    "type": "telegram",
    "bot_token": "YOUR_BOT_TOKEN",
    "chat_id": "YOUR_CHAT_ID"
  },
  {
    "active": "False",
    "type": "twilio",
    "account_sid": "YOUR_API_KEY",
    "auth_token": "YOUR_AUTH_TOKEN",
    "from_number": "YOUR_FROM_NUM",
    "to_number": "YOUR_TO_NUM"
  },
  {
    "active": "True",
    "type": "twitter",
    "startup_message": "False",
    "pokemon": {
        "status": "  <iv>% <cp>CP <pkmn>! (<atk>,<def>,<sta>) \n <quick_move> / <charge_move> \n Available until <12h_time> (<time_left>). \n <gmaps>"
               }
  }
]

**Comment by mentaloid** [comment]
This also occurs on ubuntu 16 and 17.

**Comment by kvangent** [comment]
This is because the logging module isn't process-safe. I am not aware of a good solution that.

**Comment by kvangent** [comment]
@boby361 I see you are at Python v2.7.1 - can you try updating and see if this fixes the problem for you?
