### ISSUE TITLE
[ENHANCEMENT] Cache gym info

### ISSUE THREAD

**Issue by wfcook** [PokeAlarm/PokeAlarm#448]
## Enhancement Description
It would be great if we could provide a table of gym names to use along with the corresponding Lat/Lon of the gym. This would allow the admin to (a) restart pokealarm without having the gym names go to 'unknown' for hours, and (b) Use locally-preferred nicknames for the gym,

## Use cases
(1) Restarting Pokealarm causes the gym names to be "Unknown" for some time
(2) Sometimes for local groups it would be handy to use the commonly-used name for the gym instead of the official name. For example, it might be better to list the gym as "Sprint Downtown" instead of having two gyms named "GET YOUR LEVEL BADGE"

## Other Links
N/A

**Comment by blsmit5728** [comment]
I am actually working on something like this but it is an Exclusion list. We have some gyms that are on Private land and we have been asked multiple times by cops not to be there. So to get them off our scanner without really strange geofences, I was thinking an exclusion list.

**Comment by kvangent** [comment]
You may be interested in checking out the gym_cache branch.

**Comment by wfcook** [comment]
Thanks kvangent, I will check that out! Rather than lat/lon, gym id's would work because we're just going to query the database for the information anyway

**Comment by kvangent** [comment]
#465
