### ISSUE TITLE
[ENHANCEMENT] Allow usage of "active": "False" in sub-sections (raids/pokemons/eggs)

### ISSUE THREAD

**Issue by bbdoc** [PokeAlarm/PokeAlarm#456]
## Description

Could you please allow usage of `"active": "False"` in sub-sections of the alarms.json file. At the moment, this is only supported at global level, thus completely disabling the alarm channel type.

## Why is this enhancement necessary or useful?

It will avoid having to double the number of config files and number of managers in case you want different alarms sent to different type of channels. Typically, if I want to send both raids and pokemons to Discord, but only Pokemons to Telegram, I currently have 2 (bad) choices 👍 

- Create a different filters.json file for Telegram and Discord... but when already running multiple managers that means multiplying number of managers by number of channel types. 
- Use a fake Telegram channel ID, which works but results in lots of attempts to connect to a non-existant channel and thus lots of errors in logs.

## How can this enhancement be accomplished?

Allow usage of "active": "False" in sub-sections (raids/pokemons/eggs)

**Comment by billyjbryant** [comment]
@bbdoc could you elaborate on your request?  Potentially showing an example of what you envision the alarms file looking like. 

I'm trying to understand the way it should work, as currently, the system works by simply removing the sub-section you no longer wish to use.

**Comment by bbdoc** [comment]
Hi,

Here is a simple example : 

```
[
  {
    "active": "True",
    "type":"discord",
    "webhook_url":"DISCORD_WEBHOOK_URL_FOR_FALLBACK",
    "startup_message":"False",
    "pokemon":{
      "active":"True",
      "webhook_url":"DISCORD_WEBHOOK_URL_FOR_POKEMON_CHANNEL",
      "username":"<pkmn>",
        "title": "[<neighborhood>] <pkmn> (<iv>% <atk>/<def>/<sta>, <quick_move> / <charge_move>) at <address> <postal>",
      "url": "<gmaps>",
      "body": "Available until <24h_time> (<time_left> remaining)"
    },
  "raid": {
      "active":"False",
      "webhook_url":"DISCORD_WEBHOOK_URL_FOR_RAID_CHANNEL",
      "username": "Raid",
         "title": "Level <raid_level> Raid is available against <pkmn>!",
      "url": "<gmaps>",
      "body": "The raid is available until <24h_time> (<time_left>)."
    }
  },
```

In the example above pokemons would be sent to the discord, but raids would not be sent.

In current version you cannot set "active":"True", at the pokemon or raid level, you can only set it globally at discord level. It also doesn't work to simply remove the raid section as it will throw an error on startup. Of course you can remove raids or set them to False in fitlers.json, but I'm running multiple managers with a different alarms.json file for each manager but all using the same filters.json.

**Comment by kvangent** [comment]
He want's to be able to disable alarms at an alert level - currently active is at a alarm level only.

This request shouldn't be necessary after 3.5.

**Comment by bbdoc** [comment]
@kvangent What is changing in 3.5 regarding this ?

**Comment by bbdoc** [comment]
Coming back on this one as it's still not possible in v3.5 : 

```
2018-01-12 15:29:16,473 [    MainProcess][     Utils][   ERROR] Unknown parameters at 'Alert level in Discord alarm.:
2018-01-12 15:29:16,473 [    MainProcess][     Utils][   ERROR] [u'active']
```

I know in a way custom_dts would allow to pass this as an argument but it then links back to the feature request I created that if you want to do that per goefence you need to replicate this custom_dts in every filter.

Why not allow to disable it at the alert level ?

Thanks

**Comment by kvangent** [comment]
Rules feature: https://github.com/PokeAlarm/PokeAlarm/pull/564

**Comment by billyjbryant** [comment]
This is no longer necessary with the upcoming rules feature.  Closing Issue as resolved.
