### ISSUE TITLE
[BUG/ENHANCEMENT] Ignoring neutral gyms causes gym events to be ignored completely

### ISSUE THREAD

**Issue by wfcook** [PokeAlarm/PokeAlarm#459]
## Troubleshooting Checklist
[x ] My RocketMap install is at the most recent version.  
[x ] My PokeAlarm install is at the most recent version.  
[x ] I've already checked the

## Problem Description
When ignore_neutral == True in the gym event filter, no gym event will trigger at all unless the conquering player manages to get his pokemon in the gym BEFORE RocketMap scans it as Neutral. Thus, conquered gyms often fail to cause PokeAlarm to send an alert.

## Environment
Operating System: All
Python Version: 2.7
PokeAlarm Branch: master
PokeAlarm Version: Current, updated yesterday, not at that computer right now

## PokeAlarm Setup:
Your filters file: 
    "gyms":{
        "enabled":"False",
        "ignore_neutral":"True",
        "filters":[
            {
                "from_team":["Valor", "Instinct", "Mystic"], "to_team":["Valor", "Instinct", "Mystic"],
                "min_dist":"0", "max_dist":"inf"
            }
        ]
    },

## Description
When ignore_neutral == True in the gym event filter, gym events often do not trigger an alert when the gym changes teams.

I believe (assume *cough*) that what is happening is that what is happening is that RocketMap is detecting both gym team changes from, e.g., Valor to Neutral and then from Neutral to Instinct, and does not alert on either case because "ignore_neutral":"True". This can happen even though the gym only stays neutral for a very brief period of time.

## Why is this enhancement necessary or useful?
The only current way to get alerts for all gym events is to turn off ignore_neutral, which results in *most* gym events alerting twice in rapid succession.

## How can this enhancement be accomplished?
My first-cut answer would be to have some sort of user-settable timeout in place of ignore_neutral. Something like "ignore_neutral":"300" would ignore the switch from a team to neutral for 300 seconds and cache the old_team, so that if the gym got new occupants within 30 seconds PA would alarm as if the neutral state had not been detected. After 300 seconds the change to neutral would be reported by the alarm. If "ignore_neutral":"inf", it would have the same effect as setting that to True does now, and "Ignore_neutral":"0" would have the same effect as setting it to False does now.

I recognize that this is quite possibly a non-trivial exercise because it involves a lot of cacheing of gym and timers firing events, but while I am a developer I don't work in Python and Web development so I'm not much help for evaluating the difficulty of this enhancement in this environment.

**Comment by kvangent** [comment]
Can I get some more info on this? Are you saying that when ignore_neural is set, you aren't getting notifications when gyms change teams? I'm a little confused by the wording of event.

**Comment by blsmit5728** [comment]
I am seeing some thing similar to this, maybe not similar, but along the same lines
What I am seeing is that even with "ignore_neutral : False" I am not getting double triggers like I would expect. 

Ignore my extra debug from my custom code, it should not be interfering though, I am not changing any data, only pulling from a new source to set Gym Names based on a CSV. 

> 2017-11-02 07:01:17,645 [    raid_server][   Manager][    INFO] Sableye ignored: no filters are set
2017-11-02 07:01:20,528 [    raid_server][   Gymlist][    INFO] Checking for gym location using key: 39.538412,-76.993543
2017-11-02 07:01:20,529 [    raid_server][   Manager][    INFO] Gymlist ID: 63
2017-11-02 07:01:20,529 [    raid_server][   Manager][    INFO] A=Community Media Center,B=Westminster,C=39.538412,D=-76.993543
2017-11-02 07:01:20,529 [    raid_server][   Manager][    INFO] Gym rejected: Neutral as current team is not correct (F #0)
2017-11-02 07:01:28,228 [    raid_server][   Manager][    INFO] Sableye ignored: no filters are set
2017-11-02 07:01:28,495 [    raid_server][   Manager][    INFO] Sableye ignored: no filters are set
2017-11-02 07:01:38,964 [    raid_server][   Manager][    INFO] Sableye ignored: no filters are set
2017-11-02 07:01:42,773 [    raid_server][   Manager][    INFO] Sableye ignored: no filters are set
2017-11-02 07:01:42,905 [    raid_server][   Manager][    INFO] Sableye ignored: no filters are set
2017-11-02 07:01:52,100 [    raid_server][   Manager][    INFO] Sableye ignored: no filters are set
2017-11-02 07:01:54,173 [    raid_server][   Manager][    INFO] Sableye ignored: no filters are set
2017-11-02 07:02:13,015 [    raid_server][   Manager][    INFO] Sableye ignored: no filters are set
2017-11-02 07:02:18,804 [    raid_server][   Gymlist][    INFO] Checking for gym location using key: 39.538412,-76.993543
2017-11-02 07:02:18,804 [    raid_server][   Manager][    INFO] Gymlist ID: 63
2017-11-02 07:02:18,804 [    raid_server][   Manager][    INFO] A=Community Media Center,B=Westminster,C=39.538412,D=-76.993543
2017-11-02 07:02:18,805 [    raid_server][   Manager][    INFO] Gym rejected: Neutral as old team is not correct (F #0)

**Comment by wfcook** [comment]
Yes, when ignore_neutral is set to true, I am not seeing alerts when the gym changes teams. My theory is that PokeAlarm is ignoring both of the following:

EVENT #1: "GET YOUR FREE TEAM PHONE SKIN is now neutral (was instinct)."
EVENT #2: "GET YOUR FREE TEAM PHONE SKIN is now Mystic (was neutral)."

- When ignore_neutral is false, Pokealarm reports both.
- When ignore_neutral is true, Pokealarm does not report an event on the gym. If, by chance, Rocketmap does not scan the gym while it is neutral, i.e. before it turns to mystic, then Pokealarm alerts on the change, but this is relatively rare. So for about 2/3 of gym events nothing is reported.

**Comment by kvangent** [comment]
I can't seem to reproduce this issue at all - team changes are working fine. Can you make sure you are up to date and don't have modified code?

**Comment by kvangent** [comment]
Alright I found the issue. If you don't have `neutral` as a from/to team it ignores it. When ignore neutral is on it used to not update the team, but now it does (probably from when raid/eggs were added).

**Comment by blsmit5728** [comment]
So work around is to add Neutral to the from/to list? Should we add some sort of hysteresis to the team change? Record the incoming time of a Team->Neutral if we get another gym_id within 1 minute and it's a Neutral->Team, fire off an alert?

**Comment by kvangent** [comment]
Short term work around: Don't use ignore neutral.

A more permanent fix is incoming.

**Comment by wfcook** [comment]
Thanks!

**Comment by kvangent** [comment]
Fixed in #465
