### ISSUE TITLE
[Feature Request] Allow geofencing on a per-alarm or per-filter basis

### ISSUE THREAD

**Issue by wfcook** [PokeAlarm/PokeAlarm#486]
## Troubleshooting Checklist
- [x ] My RocketMap install is at the most recent version.  
- [x ] My PokeAlarm install is at the most recent version.  
- [ x] I've already checked the
 [FAQ](https://github.com/RocketMap/PokeAlarm/wiki/faq) and the
 [Wiki](https://github.com/RocketMap/PokeAlarm/wiki) already.  

## Problem Description
Several users have asked for a separate discord channel that would alert all raids at gyms where EX raids are known to occur. The only way to do this currently is to run a separate instance of RocketMap feeding to a separate instance of PokeAlarm. It would be great to be able to simply specify a geofence on a per-manager basis instead of for the whole PA instance.

**Comment by billyjbryant** [comment]
You can already do this. Map your Geofence in an array like your Managers. Geofences are a 1 to 1 map just like filters and alerts.

**Comment by kvangent** [comment]
Specifically, check out the section on Geofences on the Manager page [here](https://github.com/PokeAlarm/PokeAlarm/wiki/managers#geofences).

**Comment by wfcook** [comment]
Yep, missed that detail, thanks
