### ISSUE TITLE
[ENHANCEMENT] DTS changing text colour in Telegram

### ISSUE THREAD

**Issue by tolukolvi** [PokeAlarm/PokeAlarm#488]
## Description
Changing colour of DTS information eg. automatically have raid announcements in the colour of the gym-owning team.

## Why is this enhancement necessary or useful?
Would provide easy and convenient way for TG-users to know which team owns the gym and choosing raids that are going on in their teams' gyms.

**Comment by kvangent** [comment]
While I like the idea of this feature, telegram doesn't offer any support for it via there api.
