### ISSUE TITLE
[ENHANCEMENT] Allow configurable icon_base_url

### ISSUE THREAD

**Issue by bbdoc** [PokeAlarm/PokeAlarm#489]
## Description

Would it be possible to add an `icon_base_url` to config.ini that would override the image repository (currently hardcoded in utils.py).

## Why is this enhancement necessary or useful?

That would allow to : 
- remove the link between PokeAlarm code and image repository as the only link would be done through config. Currently value for the image repository is clearly hardcoded.
- allow people to change image repository by only changing one parameter in config.ini, instead of having to change `icon_url` and `avatar_url` for every alarm type in every of their alarms.json. Would clearly simplify configuration.

## How can this enhancement be accomplished?

- Add  `icon_base_url`  as a configuration item in config.ini
- Use this config item in utils.py instead of currently hardcoded value

**Comment by kvangent** [comment]
Closing - this is an older issue without a lot of requests or feedback. If you feel strongly that this issue would be valuable in PA, please open a new issue.
