### ISSUE TITLE
Enhancement Request. <trainer_name> available for notifications

### ISSUE THREAD

**Issue by CRAKD** [PokeAlarm/PokeAlarm#497]
## Description

I would like poke alarm to add a <trainer_name> code for the trainer names that are in a gym. 
## Why is this enhancement necessary or useful?

to add to the notification about a specific team gym was taken by <trainername> I think this would be a fun feature. lots of turf wars in my area but we are all friendly but I think this feature would add a new dynamic to the game. 

## How can this enhancement be accomplished?

rocket map includes the trainer names that are currently in a gym in the web hook. #

**Comment by kvangent** [comment]
Thanks for your request, but I'm firmly against adding trainer names because of the potential for abuse. 

As far as I know, RM doesn't send trainer names in the gym webhook. However, even if they did, PA would not make use of it.

**Comment by CRAKD** [comment]
Fair enough it’s your world I’m just enjoying the fruits of your labor. I think there are plenty of people who could enjoy this feature maturely but i understand. Thanks for the reply.
