### ISSUE TITLE
Encountered error while getting reverse location data (TransportError: Operation on destroyed loop)

### ISSUE THREAD

**Issue by Dracon23** [PokeAlarm/PokeAlarm#513]
## Troubleshooting Checklist

- [x] My RocketMap install is at the most recent version.  
- [x] My PokeAlarm install is at the most recent version.  
- [x] I've already checked the
 [FAQ](https://github.com/RocketMap/PokeAlarm/wiki/faq) and the
 [Wiki](https://github.com/RocketMap/PokeAlarm/wiki) already.  

## Problem Description
Reverse Geocoding lookup fails at random with error message seen in the title regardless of type (noticed it happening for mons spawning and raids/eggs).

Subsequent lookups or manual checks at those coordinates get through without issues and yield a result just fine.

## Environment
Operating System: `Manjaro Linux `
Linux MercuryEuropa 4.12.14-1-MANJARO #1 SMP PREEMPT Wed Sep 20 10:51:00 UTC 2017 x86_64 GNU/Linux
Python Version: `Python 2.7.14`  
PokeAlarm Branch: `dev`  
PokeAlarm Version: `d9fba9e649c98a76865b9d1b3082e8e98f05323f`  

## PokeAlarm Setup:
Your config file: [config.ini on dpaste.de](https://dpaste.de/HeQL)  

I don't really want to upload my complete directory structure for filters and alarms (as that would be a mess of links, and operation is normal unless that error pops up, random as it is. It doesn't affect the alarm happening, it just results in address coming up as unknown ??? for <.street> <street_num> DTS pattern.

Will provide an example if really neccessary.

## Log Output
https://dpaste.de/v0KR

**Comment by Dracon23** [comment]
To clarify: I am well aware that there are locations where requests WILL result in this. I am fine with that happening on those.

What caused me to file this issue is this pattern happening, for example, gyms smack dab in the middle, that result in having an address normally, or even if I request a location for this with the gmaps module manually.

Just as an example: [Lookie me, I'm a piccie](https://i.imgur.com/zIKiQqB.png)

**Comment by kvangent** [comment]
Just to clarify, you are getting and egg where the reverse geocoding works, but then the same raid doesn't? Did you restart in between?

Also, can you run `pip freeze` to get the gmaps version and verify with `git status` that no files have been modified?

**Comment by Dracon23** [comment]
Well, git status will show telegram alarm modified, as I swapped from HTML to MD. Other then that it should be fine.

[Console output](https://dpaste.de/gDR6)

**Comment by kvangent** [comment]
Can you verify that the example you linked above occurred without a restart of PokeAlarm? Or did you restart it in between?

**Comment by Dracon23** [comment]
I did not restart in between.

In fact the raid itself came from the same egg.

I normally only restart when modifying the configuration file.
