### ISSUE TITLE
[ENHANCEMENT] Telegram should use markdown

### ISSUE THREAD

**Issue by Dracon23** [PokeAlarm/PokeAlarm#514]
## Description
Telegram supports two parse modes for it's messages, A config item would be nice to be able to toggle between those two.

## Why is this enhancement necessary or useful?
HTML alarms can turn rather ugly if you do not escape properly. Plus they increase file size unneccessarily.

## How can this enhancement be accomplished?
A setting like use_markdown which takes a bool([parse_boolean](https://github.com/PokeAlarm/PokeAlarm/blob/42da5eb023d186cbd485081b9edcea052c96eb80/PokeAlarm/Utils.py#L33)), or parse_mode which takes a string.

**Comment by Dracon23** [comment]
I'd be right with you on markdown being the standard, but a depreciation time should be considered for people having HTML still in place.

If it's not too much, have an option for one or two patch releases, then go full blown MD.

**Comment by kvangent** [comment]
https://github.com/PokeAlarm/PokeAlarm/pull/556 implements this
