### ISSUE TITLE
Don't parse disabled filters

### ISSUE THREAD

**Issue by Dracon23** [PokeAlarm/PokeAlarm#530]
## Description
If I don't enable a filter, I consider it a waste of computation time to actually parse it. Why does PAlarm do so?

## Why is this enhancement necessary or useful?
Using dev branch, config items changed. I don't really bother updating parts of a filter config I don't use in that particular manager, PAlarm doesn'T care it's disabled and refuses to start, so I have to modify configs on updating the software that I don't otherwise use.
## How can this enhancement be accomplished?
Check enabled state of the config for the manager, if it isn't "true", don't further do further parsing on it.

**Comment by kvangent** [comment]
For parsing, PA has to parse the entire file (that's just how JSON works).

As for processing those filters (and throwing errors when they are wrong) I have no plans to change. In the future it may be an option to enable/disable on the fly.
