### ISSUE TITLE
[ENHANCEMENT] Delete corrupt cache files automatically

### ISSUE THREAD

**Issue by tomballgithub** [PokeAlarm/PokeAlarm#544]
## Description

Sometimes when you go to start PokeAlarm it crashes with an EOFerror on a specific cache file.  Deleting the cache file allows execution to continue although if there are subsequent corrupt cache files the program will stop again.

PokeAlarm should catch this condition and delete the file and allowed execution to continue.

Current functionality breaks startup scripts...

**Comment by kvangent** [comment]
It's worth pointing out that if you have your caches corrupting often, you probably aren't shutting PA down correctly.

**Comment by tomballgithub** [comment]
Agreed.  I've never seen it happen when I brute force close a TMUX window and relaunch.  I've only seen it when my PokeAlarm crashes (or is closed by Ubuntu due to low memory?) and then I come along later to restart it and there are corrupt files.

**Comment by billyjbryant** [comment]
Maybe we can write a function that checks if the cache file can be loaded, if it fails, it overwrites the cache file and continues loading.

**Comment by kvangent** [comment]
We should do that, and we should write to a different file and then rename it over the original to prevent this from happening.

**Comment by kvangent** [comment]
https://github.com/PokeAlarm/PokeAlarm/pull/606
