### ISSUE TITLE
[ENHANCEMENT] Allow global usage of custom_dts

### ISSUE THREAD

**Issue by bbdoc** [PokeAlarm/PokeAlarm#547]
## Description

I would like to be able to create custom_dts at a global level while it currently only accepts custom_dts to be created inside an existing filter.

## Why is this enhancement necessary or useful?

Because some custom_dts you might want to create apply to all filters, so creating them inside a filter section means you have to multiply the number of filters by the number of custom_dts you need, which can quickly because enormous.

Typical example is that I would like to create a custom_dts based on geofences to match with my different webhook_url. I have a different url per goefence. So I would like to be able to input something like this : 

```
{
            "Zone1": {
                "geofences": ["ZONE1"],
                "custom_dts": {
                    "webhook_pkm": "11111",
                    "webhook_gym": "22222",
                    "telegram_id": "@33333"
                }
            },
             "Zone2": {
                "geofences": ["ZONE2"],
                "custom_dts": {
                    "webhook_pkm": "44444",
                    "webhook_gym": "55555",
                    "telegram_id": "@66666"
                }
 }
```

but those custom_dts should apply whatever filter triggers an alarm.

## How can this enhancement be accomplished?

PA currently supports Monsters, Stops, Gyms, Eggs, and Raids as Event types. I would suggest to create another event type called "Global" that would be triggered everytime but would not trigger an additional alarm in itself. This way we can place custom_dts in this global section and know they will be created whatever other event triggers an alarm.

Another way would be to allow for another file custom.json to be created that would contain all global custom_dts.

**Comment by kvangent** [comment]
I'm not quite sure what you are asking for here. The "defaults" section already applies custom DTS to all filters in that section - and I'm not sure what adding a 'Global' event would do.

**Comment by bbdoc** [comment]
The issue is that if you want to link a custom_dts to a filter (typically have a different custom_dts per geofence), the only way you can achieve this is in the filter sections, but those filters are triggering alarms, and if you have 50 different filters that you need to apply to 50 different geofences as you are splitting your alarms per region, you only have 2 choices : 
- Using 50 separate managers (which means maintaining 50 alarms.json).
- Create a filter for each combination of filter + geofence (e.g. iv90%_zone1, iv95%_zone2, ...). In my example that means you need 2500 filters.

What I would like is the ability to create custom_dts based on geofence filters, without triggerring any alarm but that would apply to all normal alarms, so I could create those 50 zones / custom_dts associations only once + create my 50 filters, and have it all work from a single manager.

Adding it to the default section might not be the best way, maybe adding that in rules, or in an additional similar files where we could create geofences/custom_dts associations would be best.

**Comment by kvangent** [comment]
You don't need to maintain 50 alarms.json if you are using custom_dts to trigger them - you can reuse the same alarms.json. You would need 50 different filter.jsons, but assuming you are using the same 50 filters for all 50 regions you can put the `geofence` and `custom_dts` sections in the defaults, and then just copy the filters.json and update those two parameters. 

The other thing you could do is name the geofence with the custom DTS you want to use, and use the <geofence> tag.

I understand you are looking for a way to associate `geofence` and `custom_dts` but their really isn't a good way to do it because they are all bound to a filter. I'm open to better ways to do this, but nothing suggested in this thread so far is really implementable without breaking other things.
