### ISSUE TITLE
[BUG] Twitter shortening is not working correctly.

### ISSUE THREAD

**Issue by MeTheBosss** [PokeAlarm/PokeAlarm#550]
## Description
 I would like to see the 'status' parameter string in the twitter section of alarms.json allow a longer-length string.  It appears to get cut off after 120 characters.

I have this line in my twitter section of alarms.json 

"pokemon":{
	"status":"<mon_name><form_or_empty>! CP <cp> (L<mon_lvl>), IV <iv>% (<atk>/<def>/<sta>), <quick_move>/<charge_move>. Til <12h_time> (<time_left>). <gmaps>"
},

And this shows in the twitter feed: 

Carvanha! CP ? (L?), IV ???% (?/?/?), unknown/unknown. Til <12h_thttp://maps.google.com/maps?q=38.39327347202685,-120.95277697762732

If I shorten the status string in alarms.json, like this:

"status": "<mon_name>!  CP <cp> (L<mon_lvl>), IV <iv>% (<atk>/<def>/<sta>), <quick_move>/<charge_move>. Til <12h_time>. <gmaps>"

then the tweet is not cut off and appears correctly as this with a map link at the end:

Carvanha! CP ? (L?), IV ???% (?/?/?), unknown/unknown. Til 10:10:46pm. 

## Why is this enhancement necessary or useful?
 It will allow user to display all of the desired info. on twitter.  This 'status' string contains dts values, so it is not the actual length of the status that will get tweeted.  It could be shorter or longer than the actual tweeted status, so a 120 character length is too restrictive.

**Comment by kvangent** [comment]
This is because twitter used to limit to 140 characters and people were getting the gmaps links cut off. So instead of flattening to a flat 140 characters, we strip the gmaps url, shorten the characters, and append the gmaps url again.

Is 240 characters open for everyone now?

**Comment by MeTheBosss** [comment]
Hi and thanks.  Other than the new 240 char twitter limit, I was making the point that the string before DTS is not the same length as the string after DTS, so the limit should apply to the string post-DTS.  For exampe <form_or_empty> will translate to max 1 character.

**Comment by davieau** [comment]
I'm experiencing this issue as well. It seems odd to me that truncation would be the issue since my Tweets often vary much more than the single character added by <form_or_empty>. The resulting tweet also actually seems to be longer due to the fact that the URL shortening is not applied.

**Comment by kvangent** [comment]
Please feel free to try this out and give me some feedback: https://github.com/PokeAlarm/PokeAlarm/pull/575

**Comment by davieau** [comment]
I'm having some trouble running these changes. Has the alarms format been
updated?

2018-01-26 09:14:24,618 [    MainProcess][     Utils][   ERROR] Unknown
parameters at 'Alarm level in Twitter alarm.:
2018-01-26 09:14:24,618 [    MainProcess][     Utils][   ERROR] [u'raid',
u'pokemon']
2018-01-26 09:14:24,618 [    MainProcess][     Utils][   ERROR] Please
consult the PokeAlarm wiki for accepted parameters.

**Comment by kvangent** [comment]
Yes, per the PR:

> Please note this change includes the latest verson of dev, including the rules update. Please see here for more info on converting your alarms file: #564

**Comment by davieau** [comment]
Ah, I missed that. I was hoping I could be lazy and just replace the file.
The tweets are coming in fine with the updated DTS. Hopefully I see an
unown soon so I can confirm that is working as well. Thank you for fixing
this!

**Comment by kvangent** [comment]
You can always verify with the webhook tester.
