### ISSUE TITLE
[ENHANCEMENT] Add back Boolean filter settings for individual monsters

### ISSUE THREAD

**Issue by wickles** [PokeAlarm/PokeAlarm#557]
## Description

Add back (optional) Boolean filter settings for individual monsters, like it used to work, e.g. 
```
        "Bulbasaur":"False",
        "Ivysaur":"False",
        "Venusaur": "True",
        "Charmander":"False",
        "Charmeleon":"False",
        "Charizard":"True",
```
If a name/id is specified but no boolean value is given, it could default to true to be compatible with current format. 

## Why is this enhancement necessary or useful?

The old way was much easier for handling quick changes. With the new filter format I have to delete all the names/IDs that I don't want -- then if I decide I do want it back later, I have to go look up the exact spelling or ID, instead of just finding it already listed and changing the boolean value.

## How can this enhancement be accomplished?

Use the old code for monsters, if possible.

**Comment by kvangent** [comment]
The whole underlying system for filters was changed with v3.5 to optimize speed and ease in filtering, and it's not really possible to just revert it back and keep this functionality (hence the change.)

If this is really that much of an issue for you, you could do something like the following:
```json
        "Charmander": {"monsters": [ ] },
        "Charmeleon": {"monsters": [ ] },
        "Charizard": {"monsters": [ "Charizard" ] },
```
(In the above case Charmander and Charmeleon can never pass, so they are effectively set to "False")

**Comment by wickles** [comment]
The old method was far more easily maintainable for me as an alerts server admin. I understand that it would not be possible to just revert back, but if there is some way that it could be cleanly implemented in the new system (without requiring hundreds of individual filters to flood CLI output), it would be highly highly appreciated.
