### ISSUE TITLE
Markdown doesn't work in Venues

### ISSUE THREAD

**Issue by lucholapl** [PokeAlarm/PokeAlarm#569]
## Troubleshooting Checklist

- [X] My RocketMap install is at the most recent version.  
- [X] My PokeAlarm install is at the most recent version.  
- [X] I've already checked the
 [FAQ](https://github.com/RocketMap/PokeAlarm/wiki/faq) and the
 [Wiki](https://github.com/RocketMap/PokeAlarm/wiki) already.  

## Problem Description

Using the dev Branch, with the new Telegram adapted to markdown parse_mode, there is a bug when using "venue"="true" and the message is too long to fit inside a whole message box, as seen in this picture.
![image](https://user-images.githubusercontent.com/19576035/35285330-fd8be0ca-0054-11e8-9ade-3ad8860f7068.png)
As seen, the "message" tag from the Telegram Alarm is seen as "title" and "body" from the previous versions, getting the first line bolded (ignoring the * from markdown's syntax)

## Environment
Operating System: `Not relevant `  
PokeAlarm Branch: ` dev ` 
PokeAlarm Version: `last `  

## PokeAlarm Setup:

Your config file: `Not relevant `  
Your filters file: `Not relevant `  
Your alarms file: 
```    {
	"active": "True",
	"type":"telegram",
	"bot_token":"BOT TOKEN HERE",
	"startup_message": "True",
	"chat_id":"<channel_api_key>",
	"monsters" : {
		"message": "*<iv>% (<atk>/<def>/<sta>) - <mon_name><form_or_empty> <gender>*\nZona:*<geofence>*\n<street>, <street_num>\nCP:*<cp>*Nivel:*<mon_lvl>*\nHasta las *<24h_time>* (<time_left>)",
		"`venue": "True"
	}
  },

**Comment by kvangent** [comment]
@lucholapl Markdown doesn't work in venues - this isn't PA's fault, but a limitation of Telegram's api. HTML doesn't work either You can read more here: https://core.telegram.org/bots/api#sendvenue

@MARTINI1 Would you please update the wiki for telegram to reflect this?

**Comment by MARTINI1** [comment]
done, added note in wiki
