### ISSUE TITLE
Configurable Startup Message for Alarms

### ISSUE THREAD

**Issue by LiteABong** [pokealarm/pokealarm#574]
## Description

It would be nice to be able to edit the alarm system startup message like a regular alarm. As in change the avatar, poster name & content

## Why is this enhancement necessary or useful?

For those that don't run IVs all the time, this would be a really way to notifying the users that IVs have been activated. Adding the content field would allow the mapper to tag the specific users/channels.

## How can this enhancement be accomplished?

Apply the same logic used to build other alarms to obtain the additional functionality.

**Comment by billyjbryant** [comment]
@kvangent Think this could be something added at the Alert level and possibly configured to use `custom_dts`?

**Comment by kvangent** [comment]
Right now, the primary purpose of the of the start up message is diagnostic. In order to customize it, it would probably easiest to add a new alert field.
