### ISSUE TITLE
[ENHANCEMENT] Support 'gym_name_doesnt_contain'

### ISSUE THREAD

**Issue by tomballgithub** [PokeAlarm/PokeAlarm#585]
## Description

Gym_name_contains has been added to be able to detect certain gyms by name and direct them into feeds.  An example of this would be for sponsored raids and specifically named gyms

I propose that we also have the ability to exclude gyms with specific names.  An example of this would be for a map that has gyms that are not accessible for raids or for which the location has requested that their gym not be publicized for raids.  For instance, I have some personal code to do exactly this and exclude gyms by name (it's a hack) but then I thought this feature goes hand in hand with the gym_name_contains feature but it would be 'doesnt_contain' (or whatever the right name is)

**Comment by tomballgithub** [comment]
testing this.  I couldn't find your exact regex for exclusion online but I am still trying yours first.  One limitation is I think you can only exclude one term instead of multiple terms but for my purposes it should work.

**Comment by kvangent** [comment]
Multiple regexs would be `((?!(regex1)|(regex2))).*`

**Comment by tomballgithub** [comment]
I've testing the single version and it works.  Let's leave this open until myself or someone else updates the Wiki page to provide this information as an example.  I will put it on my to-do list

**Comment by MARTINI1** [comment]
@tomballgithub to multiple terms or gym name you can use:
"gym_name_contains":["^(.(?!(Gym name1)))*","^(.(?!(Gym name2)))*"]

I'm using it from the dev of 3.6 and it works

**Comment by kvangent** [comment]
@MARTINI1 I don't think that would work like you think since you would only need to match one regex to pass.

**Comment by kvangent** [comment]
#611 (FYI @tomballgithub, @MARTINI1)

**Comment by tomballgithub** [comment]
LOL just today I modified my filters file to permanently use the REGEX method instead of the PR I had created.
