### ISSUE TITLE
[BUG] Telegram Sticker small

### ISSUE THREAD

**Issue by Shokoboko** [PokeAlarm/PokeAlarm#587]
since i updated to 3.6 telegram egg stickers are realy small:

small egg sticker:
![grafik](https://user-images.githubusercontent.com/20883163/35514464-8af8fcbc-0506-11e8-8722-0267b97ec5d1.png)

normal sticker on monsters:
![grafik](https://user-images.githubusercontent.com/20883163/35514467-9127db8a-0506-11e8-8fb1-c1f697cefa24.png)

**Comment by kvangent** [comment]
Should be fixed in https://github.com/PokeAlarm/PokeAlarm/commit/fb66d042f883c046d59d1b881c991d3aff7ee196.
