### ISSUE TITLE
[ENHANCEMENT] Add toggle to enable web page preview in Telegram messages

### ISSUE THREAD

**Issue by Alexus230** [PokeAlarm/PokeAlarm#595]
## Description
From patch 3.6 PokeAlarm sends all messages to Telegram with option 'disable_web_page_preview'. Please add toggle to enable web page preview in Telegram messages.

## Why is this enhancement necessary or useful?
In my setup I use web page preview feature to include pokemon image inside a message. This trick help me reduce the amount of messages, because when stickers was enabled, I got 3 messages (sticker,message,map) on every event, but with this trick I got only 2 messages (message,map).

**Comment by kvangent** [comment]
@Alexus230 #620
