### ISSUE TITLE
[BUG] Geofences checking is not in order

### ISSUE THREAD

**Issue by Buncertainc** [PokeAlarm/PokeAlarm#601]
## Troubleshooting Checklist

- [x] My RocketMap install is at the most recent version.  
- [x] My PokeAlarm install is at the most recent version.  
- [x] I've already checked the
 [FAQ](https://github.com/RocketMap/PokeAlarm/wiki/faq) and the
 [Wiki](https://github.com/RocketMap/PokeAlarm/wiki) already.  

## Problem Description

Geofence is not checking in the order that I have set in my filters.
For example:
I have set [a,b,c,d] in geofences section of a filter
However, PA is checking geofences in [b,d,c,a] order

I have tried to set the order in the geofence.txt like:
[a]
xxx,xxx
[b]
xxx,xxx
....
but PA also doesn't follow this order when it checks the geofences.

## Environment
Operating System: ` Ubuntu 16.04 `  
Python Version: ` 2.7.12 `  
PokeAlarm Branch: ` master `  
PokeAlarm Version: ` ba3c1d7b5d13c50961b5d0637456f99a2ba4ac35 `  

## PokeAlarm Setup:

Your config file:   
Your filters file:   
Your alarms file:

**Comment by kvangent** [comment]
@Buncertainc Feel free to try this out: https://github.com/PokeAlarm/PokeAlarm/pull/604

**Comment by Buncertainc** [comment]
It works.
Thanks a lot.
