### ISSUE TITLE
Flock Messenger

### ISSUE THREAD

**Issue by nmilitello** [PokeAlarm/PokeAlarm#605]
## Troubleshooting Checklist

- [ ] My RocketMap install is at the most recent version.  
- [ ] My PokeAlarm install is at the most recent version.  
- [ ] I've already checked the
 [FAQ](https://github.com/RocketMap/PokeAlarm/wiki/faq) and the
 [Wiki](https://github.com/RocketMap/PokeAlarm/wiki) already.  

## Environment
Operating System: ` YOUR OPERATING SYSTEM HERE `  
Python Version: ` (obtained from `python -V`) `  
PokeAlarm Branch: ` ex: master, dev, other `  
PokeAlarm Version: ` (`git rev-parse HEAD` inside PA folder) `  

## PokeAlarm Setup:

Your config file:   
Your filters file:   
Your alarms file:

**Comment by nmilitello** [comment]
Would it be possible to have PA report to Flock Messenger?

**Comment by kvangent** [comment]
We use a single issue for requests to new services: https://github.com/PokeAlarm/PokeAlarm/issues/147

Please post the name of the service as well as a link to the API documentation.
