### ISSUE TITLE
[BUG] The <team_name> DTS is not working for Raids/Eggs after 3.5 (Monocle)

### ISSUE THREAD

**Issue by billyjbryant** [PokeAlarm/PokeAlarm#607]
## Troubleshooting Checklist

- [x] My Monocle install is at the most recent version.  
- [x] My PokeAlarm install is at the most recent version.  
- [x] I've already checked the
 [FAQ](https://github.com/RocketMap/PokeAlarm/wiki/faq) and the
 [Wiki](https://github.com/RocketMap/PokeAlarm/wiki) already.  

## Problem Description
When using Monocle (Hydro) as scanner, the `<team_name>` DTS is not working for Raid/Egg Events since 3.5. 

![image](https://user-images.githubusercontent.com/3013565/36166572-e6e821ae-10c0-11e8-86cb-9f73e20e50f2.png)

## Environment
Operating System: ` Debian 9 Stretch `  
Python Version: ` Python 2.7.13 `  
PokeAlarm Branch: `dev `  
PokeAlarm Version: `6874372dbe34db417d3f7e8a774a593f8279c244 `  

## PokeAlarm Setup:

Your config file:   
Your filters file:   
Your alarms file:

**Comment by kvangent** [comment]
Can you try https://github.com/PokeAlarm/PokeAlarm/pull/606 and see if the problem goes away?

Also can you get me some fresh payload captures from Monocle so I can verify we are getting the information correctly?
