### ISSUE TITLE
[ENHANCEMENT] Actual estimated walking/driving/bike time to alert location

### ISSUE THREAD

**Issue by YellowZaki** [PokeAlarm/PokeAlarm#636]
## Description

I would like a new DTS for Telegram that allow us to click on a buttom in order to receive a private message from the bot to know the Estimated walking/driving/cycling time from the user who has clicked  , to the alert location.
I don't know if this can be done without using private messages, like a floating message only visible to the player who has clicked. I also guess that it can be done on Discord (I only use Telegram, so I don't know about Discord a lot).

## Why is this enhancement necessary or useful?

The current <walk/cycling/driving_time> DTS is useless. Why would I want to know the time from a spot that is already set? I want to know the time from my position.
This way, users would know if they can arrive on time for a pokemon.
Personally, I always launch Google Maps to see if I would arrive on time.

## How can this enhancement be accomplished?

Get user's location: https://core.telegram.org/bots/api/#keyboardbutton

It seems that in only can be used in private chat, so when you click the button on the channel, the bot would message you: [Click here to know the time]

Here is the concept:

The user receive the alert with the button.

![11](https://user-images.githubusercontent.com/13599841/36928553-108e0d4c-1e87-11e8-9485-59d1838921f2.png)

The user clicks the button and receive this private message.

![22](https://user-images.githubusercontent.com/13599841/36928572-2df8a112-1e87-11e8-9cd7-d21ce936ba47.png)

**Comment by kvangent** [comment]
This is not actually possible because PA doesn't behave like a regular bot - it only sends information to telegram, but it doesn't take any information back.

It is out goal to add an API to PA so that you may configure settings on the fly - including changing location as you move about. Perhaps this will make the distance matrix DTS more useful for you.
