### ISSUE TITLE
[User Issue] Variable Stickersize

### ISSUE THREAD

**Issue by DerMoonbreaker** [PokeAlarm/PokeAlarm#642]
The Pokealarm works very greate with Telegram

But the Stickers are so big. They take nearly 25% of the displaysize . 
Is it posible to add a new parameter in the Alarm.json called sticker_size_percent so i can make it smaller?

**Comment by kvangent** [comment]
PA can't set the sticker size - Telegram requires stickers be 512x512.

Please use the correct form when submitting an issue.
