### ISSUE TITLE
[ENHANCEMENT] Trainer Name Alert

### ISSUE THREAD

**Issue by Thpathpa** [PokeAlarm/PokeAlarm#643]
## Description
It would be cool to have alarm on any trainer name written in a list. When this person add pokemon in our gym area, we will receive a notification.

## Why is this enhancement necessary or useful?
To be alerted when any of your black-list trainer is taking a gym.

## How can this enhancement be accomplished?
I think put a list of any trainer we want to be alerted on taking a new gym.
Then add DTS in Gym flag: <trainer_name>

**Comment by billyjbryant** [comment]
This is not possible as none of the current scanners send this information with the webhooks.  This is also not a feature we plan on implementing.
