### ISSUE TITLE
[ENHANCEMENT] Configure Locales at alarms or rules level

### ISSUE THREAD

**Issue by bbdoc** [PokeAlarm/PokeAlarm#646]
## Description

Would it be possible to move/add the locale parameter, currently set at manager level, to the alarm level (be able to specify a language as a parameter for an alarm in alarm.json) or at the rule level (when associating a filter with an alarm, give the possibility to also associate a language).

## Why is this enhancement necessary or useful?

I'm running in a multi-language environment and thus need to send some alarms to my channels in FR and some other in EN. I'm currently achieving this using multiple managers, one being set in FR and one in EN, each using their own geofence.txt in order to define for which region I want to send in each language. This was a logical way of doing things prior to 3.7 as I also had multiple alarm files. But as from 3.7, I have defined multiple alarms in my alarms.json (one per language) and I'm using rules in order to define which filters triggers an alarm in which language. Still, the text I've set manually is in the right language, but the dts are translated in the manager's language. 

Would sound more logical to me to be able to set `"locale": "fr"` at the alarms level, but adding it in rules would also fit the need. That would allow to create a fully multi language alarms.json file

It could be an overwrite on locale settings already defined in config.ini so it doesn't break current way of working while allowing the extra flexibility.

**Comment by kvangent** [comment]
This is not really possible in PA without drastically changing how the DTS are generated. Currently when an Event passes a filter, each set of DTS is generated a single time. Adding in different languages at that level would require generate the DTS multiple times.  It's something we've discussed, but don't feel it's worth the time or performance decreases to implement. 

Rules are designed to reduce the number of Managers you need and make configuring easier, but there intent isn't to replace Managers completely. They are still useful for controlling apis, langauge, or locations in a ways we don't intend to add to rules.
