### ISSUE TITLE
<mon_name> in lowercase to utilize "icon_url:"

### ISSUE THREAD

**Issue by OfficialWiddin** [PokeAlarm/PokeAlarm#647]
## Description

Currently `<mon_name>` returns as `Monster`, the first letter is uppercase.
It's very hard to utilize the alarm `icon_url:` because most of the websites are all lowercase.

## Why is this enhancement necessary or useful?

To be able to utilize more out of `icon_url` there has to be a way to retrieve the `<mon_name>` as all lowercase.

## How can this enhancement be accomplished?

By adding a DTS for something like `<mon_name_lower>` for receiving the monster name in all lowercase.

**Comment by OfficialWiddin** [comment]
`'mon_name_lower': locale.get_pokemon_name(self.monster_id).lower()`

Honestly, I have no clue, haven't worked with PokeAlarm :D

**Comment by kvangent** [comment]
I don't really think that mon_name is appropriate to use in a url - there name changes on locale and several languages have characters that aren't appropriate for urls.  Have you considered using `mon_id` or `mon_id_3` instead?

**Comment by Widdin** [comment]
I wasn't really about what you or I think is appropriate for our own website. It's more about what some web pages use if you want to utilize their pictures by using their URL.

But I solved my "issue" by finding another page hosting the images but with the IDs instead of names.
