### ISSUE TITLE
[ENHANCEMENT] Add Cleanup Process

### ISSUE THREAD

**Issue by spammer23** [PokeAlarm/PokeAlarm#648]
## Description

Add a Cleanup Process to delete old messages when:
- Pokemon despawn
- Raid ended
- Lure expired
- ...
Each cleanup can be turned on/off. Maybe with time offset (delete 5 mins after despawn)

## Why is this enhancement necessary or useful?

A raid or spawn channel would be cleaned up.
In the morning, you do not have 100+ spawns out of the night.
In Raidchannel you will find faster current raids

## How can this enhancement be accomplished?

I can't programm stuff like this, but i have seen this in some bots, so i know it is possible.
Maybe somebody finds it as useful as me

**Comment by billyjbryant** [comment]
PA is not a bot, it communicates only via webhooks; therefore, we do not keep track of the messages that are sent nor have the ability to clean these up.  You would need to use your own secondary bot to cleanup any stale messages.
