### ISSUE TITLE
Add "geofence_excludes" restriction 

### ISSUE THREAD

**Issue by FakeKitten** [pokealarm/pokealarm#652]
## Description
An exclusion geofence.

## Why is this enhancement necessary or useful?
Currently for something like ex gyms the easiest way to filter them is by name but this can cause issues where two gyms have the same name. A small exclusionary geofence around the offending gyms would be far easier than trying to geofence all acceptable gyms.

## How can this enhancement be accomplished?
Taking the code for geofences and turning it upside down.

**Comment by billyjbryant** [comment]
Why not exclude these @ the scanner so that PA just doesn't get alerted for them?

**Comment by FakeKitten** [comment]
I'd still like to know about raids at those gyms, I just have a specific filter for a ex gym channel

**Comment by billyjbryant** [comment]
This requires a major overhaul of how filters work. Right now filters are additive only not subtractive. This requires a subtractive geofences filter that would need to know a list of valid Geofences to remove the appropriate geofence. It would be much easier to create a new alert that uses the existing `geofences` filter and just excludes that geofence.
