### ISSUE TITLE
Filter By Gym ID

### ISSUE THREAD

**Issue by FakeKitten** [pokealarm/pokealarm#653]
## Description
A filter for raids/gyms that works by gym id rather than gym name

## Why is this enhancement necessary or useful?
Currently filtering for gym name is possible but this has a couple of issues; without a cache the gym name is not returned and can't be filtered, secondly two gyms can have the same name.

## How can this enhancement be accomplished?
Taking the code for gym name and making it more good.

**Comment by blsmit5728** [comment]
What if you simply had the ability to override the gym name in the cache, like say for example, set a gym name via the ID, and if it was set, the gym_info webhook would not overwrite it. I HAD a branch like this before the rework, I probably could rebase it and bring it back to life.

**Comment by FakeKitten** [comment]
For my specific purposes that would work.
I guess with that feature I could manually replace all gym names with their ID and still filter by ID.

**Comment by kvangent** [comment]
Are there really a lot of occurrences of gyms having the same name? 

It's worth point out the the cache (and thus the inability to filter by unknown gym_names) is only an issue for stock RM at the point, as all of the other scanners have properly implemented gym names on the relevant webhooks.
