### ISSUE TITLE
Add support for Python 3

### ISSUE THREAD

**Issue by kvangent** [pokealarm/pokealarm#661]
## Description
Add support for Python 3 without removing Python 2 support. 

## Why is this enhancement necessary or useful?
Python 3.7 is beginning to show significant speed improvements, and with Python 2 support ending in 2020 we should start transitioning now.

## How can this enhancement be accomplished?
Some useful references: http://python-future.org/compatible_idioms.html

**Comment by LegitDongo** [comment]
Closed with #732
