### ISSUE TITLE
Ex Eligible Gyms via Webhook cutom DTS

### ISSUE THREAD

**Issue by unseenmagik** [pokealarm/pokealarm#665]
## Description

We would like to be able to filter out raids that are happening in a gym that is Ex-Raid Eligible. 

## Why is this enhancement necessary or useful?

This will allow our members to target the Ex-Eligible gyms and have better chances of obtaining an Ex-Raid pass. 

## How can this enhancement be accomplished?

Currently we are using RocketMapPlusPlus that has been customised, of which now sends a boolean logic via webhook that PA can use to implement. 
Additonal details can be found on the #beta channel within the PA Discord Server.  
 
Barts notes: The field is a boolean field named 'is_ex_raid_eligible' and is sent in the raid webhook
Logic can be found with RM++ configuration as seen here:
https://github.com/GlobalPlusPlus/RocketMapPlusPlus/blob/pokestopmembers/pogom/app.py#L561

Many Thnks
Magik

**Comment by kvangent** [comment]
Implemented in #670.
