### ISSUE TITLE
Request: <verified_or_empty>

### ISSUE THREAD

**Issue by plinytheelder** [pokealarm/pokealarm#682]
## Description

similar to other DTS, add a <verified_or_empty> tag that, if `verified=TRUE`, DTS will return True, or preferably, a unicode check mark

## Why is this enhancement necessary or useful?

PokeAlarm has a similar feature for form, weather, etc. Why not Verified Timers?

## How can this enhancement be accomplished?

mon event

**Comment by JimBim89** [comment]
Good suggestion, maybe also add <unverified_or_empty>?

**Comment by LegitDongo** [comment]
Completed in #710
