### ISSUE TITLE
Forms show wrong type / weather / cp values

### ISSUE THREAD

**Issue by JimBim89** [pokealarm/pokealarm#683]
## Troubleshooting Checklist

- [x] My Scanner install is at the most recent version.
- [x] My PokeAlarm install is at the most recent version.
- [x] I've already checked the [FAQ](https://github.com/RocketMap/PokeAlarm/wiki/faq) and the [Wiki](https://github.com/RocketMap/PokeAlarm/wiki) already.

## Problem Description

I'm glad PA started to support form ids. The form name and pictures do properly show, but types (also affecting weather) and cp values are currently wrongly displayed/calculated.

**Comment by LegitDongo** [comment]
The form does not properly impact the type like it should.

This will require some major changes.

**Comment by kvangent** [comment]
@LegitDongo Is this something you want to include in v3 or should it wait for v4?

**Comment by LegitDongo** [comment]
I'm not entirely sure what's changing in v4, but it might be wise since we're getting v3 to be harder to keep up with change-wise.

**Comment by LegitDongo** [comment]
I'm considering working on this next

Things that would need to change:
Monster Types (in monsters and raids)
Costume information
Rarity
Catch rates (if this is still valid)
Weather information (what is boosted where)
CP ranges
Stats

The biggest amount of work will be modifying `base_stats.json` for these needs
ex.
```
{
  "001": {
    ...
    "forms": {
      "form-id": { 
         "attack": ...,
         "type1": ...
      }
    }
  }
}
```
