### ISSUE TITLE
Missing translations for moves

### ISSUE THREAD

**Issue by x3r0x** [pokealarm/pokealarm#718]
Moves are only included in the en locale, though the moves above 291 are not translated.

These are the translations for the german loacles files. (starting from line 3710)

`    "292": "Meteorologe (Feuer)",
    "293": "Meteorologe (Eis)",
    "294": "Meteorologe (Gestein)",
    "295": "Meteorologe (Wasser)",
    "296": "Flora-Statue",
    "297": "Katapult",
    "298": "Lohekanonade",
    "299": "Aquahaubitze",
    "300": "Zuflucht",
    "301": "Sternenhieb",
    "302": "Schädelwumme",
    "303": "Säurespeier",
    "304": "Erdkräfte",
    "305": "Krabbhammer",
    "306": "Anfallen",
    "307": "Zermalmklau",
    "308": "Octazooka",
    "309": "Spiegelsalve",
    "310": "Kraftkolloss",
    "311": "Stachelfinale",
    "312": "Grasmixer",
    "313": "Blutsauger",
    "314": "Ableithieb",
    "315": "Schattenknochen",
    "316": "Lehmbrühe",
    "317": "Feuerfeger",
    "318": "Kalkklinge",
    "319": "Steigerungshieb",
    "320": "Charme"	`

and for the french locales file. (starting from line 3706)

`    "292": "Ball'Météo (feu)",
    "293": "Ball'Météo (glace)",
    "294": "Ball'Météo (roche)",
    "295": "Ball'Météo (eau)",
    "296": "Végé-Attak",
    "297": "Anti-Air",
    "298": "Rafale Feu",
    "299": "Hydroblast",
    "300": "Dernier Recours",
    "301": "Poing Météor",
    "302": "Coud'krâne",
    "303": "Bombe Acide",
    "304": "Telluriforce",
    "305": "Pince-Masse",
    "306": "Furie-Bond",
    "307": "Éclate Griffe",
    "308": "Octazooka",
    "309": "Miroi-Tir",
    "310": "Surpuissance",
    "311": "Dard Mortel",
    "312": "Feuillemagik",
    "313": "Vampirisme",
    "314": "Vampipoing",
    "315": "Os'Ombre",
    "316": "Ocroupi",
    "317": "Pied Brûleur",
    "318": "Coquilame",
    "319": "Poing Boost",
    "320": "Charme"`

**Comment by billyjbryant** [comment]
#792 resolves the German locales. Need the French locales updated now.

**Comment by billyjbryant** [comment]
#788 updated FR locale, Resolving this Bug
