### ISSUE TITLE
Can't reach wiki

### ISSUE THREAD

**Issue by ire-and-curses** [pokealarm/pokealarm#735]
## Troubleshooting Checklist

- [x] My Scanner install is at the most recent version.
- [x] My PokeAlarm install is at the most recent version.
- [x] I've already checked the
 [FAQ](https://github.com/RocketMap/PokeAlarm/wiki/faq) and the
 [Wiki](https://github.com/RocketMap/PokeAlarm/wiki) already.

## Problem Description

I'd like to read the wiki. The wiki links in the README go to an empty page. Example bad link: https://pa.readthedocs.io/en/master/

I see hits for the wiki in Google but they don't work either.
![image](https://user-images.githubusercontent.com/1606404/92786970-8cebe780-f35d-11ea-9be4-feb5dc2c7209.png)

**Comment by ire-and-curses** [comment]
I guess this one works: https://pa.readthedocs.io/en/dev/ - just master with the problem

**Comment by kvangent** [comment]
We had disabled the master branch wiki, since we've pretty much switched back to a rolling release cycle and haven't been pushing updates to master. 

I enabled it, but hid it from the drop-down to encourage users to use the `dev` version instead.
