### ISSUE TITLE
Commit 90cee601de85e1cf25f97f8813ec0be07b52284d breaks stuff

### ISSUE THREAD

**Issue by gcm-explo1t** [pokealarm/pokealarm#742]
#369  Troubleshooting Checklist
- [x] My Scanner install is at the most recent version.
- [x] My PokeAlarm install is at the most recent version.
- [x] I've already checked the
 [FAQ](https://github.com/RocketMap/PokeAlarm/wiki/faq) and the
 [Wiki](https://github.com/RocketMap/PokeAlarm/wiki) already.

## Problem Description
When using the newest version (also updating requirements etc.) the program errors with:
 Traceback (most recent call last):
   File "start_pokealarm.py", line 416, in <module>
     start_server()
   File "start_pokealarm.py", line 95, in start_server
     parse_settings(os.path.abspath(os.path.dirname(__file__)))
   File "start_pokealarm.py", line 391, in parse_settings
     signal(signal.SIGINT, exit_gracefully)
 TypeError: 'module' object is not callable
 pokealarm.service: Main process exited, code=exited, status=1/FAILURE
 pokealarm.service: Failed with result 'exit-code'.

I also tried installing gevent=1.4.0 , but got the same error. After commenting out line 391 and 392 in start_pokealarm.py it worked again.

## Environment
Operating System: `Debian Buster`
Python Version: ` Python 3.7.3 `
PokeAlarm Branch: ` dev `
PokeAlarm Version: `04bd912f256d7c1ee42acf2a90b3fb514d4b5595`
Scanner used: `MAD`

## PokeAlarm Setup:
Not required

## Log Output
https://hastebin.com/junosodamo.md

**Comment by kvangent** [comment]
I believe @LegitDongo fixed this in #744
