### ISSUE TITLE
Add the variable <mon_emoji> for discord's alerts (in order to have emoji changing based on the monster)

### ISSUE THREAD

**Issue by PokeNemo** [pokealarm/pokealarm#745]
## Description
Implement a variable called `<mon_emoji>` or `<emoji_id>` (or whatever) to be used inside the json (**for discord's alerts**). PokeAlert (considering the id of the pokemon) should replace the variable with the string `<:emoji_name:emoji_id>` according to a txt/json file containing every pokemon emojis (the file is editable by the user and could be empty). In this way we can have emoji changing based on the monster.

## Why is this enhancement necessary or useful?
This enhancement is very useful because it allows me (and other pokealarm users) to use small custom pokemon emojis for discord alerts, instead of using images.

## How can this enhancement be accomplished?
This enhancement can be accomplished very easily by duplicating the already existing variable <mon_id_3> (or <mon_name>) in a new variable (you can call it `<mon_emoji>`). Then you need to build an empty txt/json file in order to have the correspondences between pokemon_id and emoji's full name (in the format `<:name:emoji_id>`).  **The user can edit (or fill) the file himself**.
Example:
```
"mon_emoji": {
"001": "<:bulbasaur:emoji_id>",
"002": "<:ivysaur:emoji_id>",
...
}
```
For my purpose, the implementation of the variable <mon_emoji> (with an empty txt/json file) is enough. I can build the file myself.
If you want to build a generic txt file for everyone and you need an help, write to me on discord. My discord ID is [<@701921670742540359>](https://discord.com/channels/@me/701921670742540359).

**Comment by LegitDongo** [comment]
Something to note here is that webhooks can use any emoji from any server, regardless of if the owner of the webhook has access to the emoji or not, so we could implement some reasonable defaults

**Comment by billyjbryant** [comment]
Is there a single Discord server that would have all pokemon emojis available we can source from?

**Comment by billyjbryant** [comment]
I think given the ability to host emojis for all Pokemon to really make this useful, and the fact that there are 898 pokemon currently, I do not see this is a feasible or highly useful change. 

No single discord server (even one that is fully boosted to Level 3) can have more than 250 emoji slots. 

For that reason, I am closing this FR
