### ISSUE TITLE
Incorrect type translation

### ISSUE THREAD

**Issue by pogoteambrindisi** [pokealarm/pokealarm#757]
The Italian translation of Pokémon types is incorrect in most cases. I provide here a list of the correct types in Italian:

Normal -> Normale
Poison -> Veleno
Psychic -> Psico
Grass -> Erba
Ground -> Terra
Ice -> Ghiaccio
Fire -> Fuoco
Rock -> Roccia
Dragon -> Drago
Water -> Acqua
Bug -> Coleottero
Dark -> Buio
Fighting -> Lotta
Ghost -> Spettro
Steel -> Acciaio
Flying -> Volante
Electric -> Elettro
Fairy -> Folletto

**Comment by LegitDongo** [comment]
Fixed with #758
