### ISSUE TITLE
GoStadium Level 50 Max URL

### ISSUE THREAD

**Issue by LegitDongo** [pokealarm/pokealarm#763]
## Description
Add a level 50 limiter for the gostadium URL

## Why is this enhancement necessary or useful?
some people like to see both level 50 and level 40 limits because of stardust/candy requirements

## How can this enhancement be accomplished?
use the same url, add a `&levelCap=50` on the end (case-sensitive)

BONUS:
`&min-iv=5`
 defines whether it is wild, trade, raid, etc

❤️ thanks RedSalsicha

**Comment by mikosoby** [comment]
[This PR](https://github.com/pokealarm/pokealarm/pull/766) solves the issue with Level 50.
