### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by jinnatar** [pokealarm/pokealarm#765]
## Troubleshooting Checklist

- [x] My Scanner install is at the most recent version.
- [x] My PokeAlarm install is at the most recent version.
- [x] I've already checked the
 [FAQ](https://github.com/RocketMap/PokeAlarm/wiki/faq) and the
 [Wiki](https://github.com/RocketMap/PokeAlarm/wiki) already.
(impossible to check the FAQ since all your links to it are stale, but GitHub search returns no results so, calling it good enough due dilligence.)

## Problem Description
- At current Python 3.8 is not supported due to a tied ancient gevent version that fails to build on Python 3.8. (8fd37f2d33a42797d563069c46f79eaeeb436823)
- A modern version (gevent-21.1.2) installs fine, but I understand PokeAlarm does not support it.
- For example the Ubuntu 20.04 LTS ships Python3.8 by default. Python 3.7 at this point is almost 3 years old and is EOL as of 2020-06-27 (although critical security updates will be available for 2+ more years.)

## Environment
Operating System: ` Ubuntu 20.04.2 LTS`
Python Version: `Python 3.8.5`
PokeAlarm Branch: `master`
PokeAlarm Version: `e72db5524f5f3580ce66b86e6d947a560c8fedc6`
Scanner used: `MAD`

## PokeAlarm Setup:
N/A

## Log Output
N/A

**Comment by jinnatar** [comment]
Actually, my bad. I assumed the master branch was not abandoned. The dev branch actually does install in python3.8. You may want to consider just deleting the master branch if it's left to rot for 3 years.

**Comment by kvangent** [comment]
I went ahead and deleted the master branch. 

It's worth pointing out that the dev branch has been marked as the default for a while though.
