### ISSUE TITLE
Fetch Base Stats and Move Info

### ISSUE THREAD

**Issue by LegitDongo** [pokealarm/pokealarm#770]
## Description
Get the base stats and move info based on an interval or on request
Allow the fetch URL to be changed

## Why is this enhancement necessary or useful?
This changes enough that we don't want to make a git commit every time they change
Also, we are pretty bad with keeping up with it

## How can this enhancement be accomplished?
A few config options, a http request, and change some data around

**Comment by billyjbryant** [comment]
@LegitDongo is allowing the URL to be configurable a hardfast requirement of this FR? Seems that changing the URL to something different that might have a different file format or data structure would fail unless you also had a way of specifying the schema of the file, which would be difficult. If this is something we can live with not being configurable by the end user, I believe we can call this request closed as #802 is already merged which pulls the data dynamically.
