### ISSUE TITLE
Gmaps discord link not opening maps on Android. Links do not comply with Google guidelines

### ISSUE THREAD

**Issue by cheveuxroux69** [pokealarm/pokealarm#785]
## Troubleshooting Checklist

- [x] My Scanner install is at the most recent version.
- [x] My PokeAlarm install is at the most recent version.
- [x] I've already checked the
 [FAQ](https://github.com/RocketMap/PokeAlarm/wiki/faq) and the
 [Wiki](https://github.com/RocketMap/PokeAlarm/wiki) already.

## Problem Description
The gmaps link generated in Utils.py is incorrect and does not open the Google maps app on my android device.
The link specification is here: https://developers.google.com/maps/documentation/urls/get-started

> Search — launch a Google Map that displays a pin for a specific place, or perform a general search and launch a map to display the results:
> https://www.google.com/maps/search/?api=1&parameters

The following code will fix the issue and display Google maps correctly. Sorry, I've tried creating a PR but it's beyond my comprehension how to do it. This code has been tested on Discord on Android and Apple devices, I don't use facebook or telegram so can't test on those platforms.

```
import sys
import urllib.parse
# 3rd Party Imports
```

```
# Returns a String link to Google Maps Pin at the location
def get_gmaps_link(lat, lng):
    latlng = '{:5f},{:5f}'.format(lat, lng)
    latlng = urllib.parse.quote_plus(latlng)
    return 'https://www.google.com/maps/search/?api=1&query={}'.format(latlng)
```

## Environment
Operating System: ` Linux 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux `
Python Version: ` Python 3.8.10`
PokeAlarm Branch: `master`
PokeAlarm Version: ` (`2edc3a978b7435a453d1917fbf436891fad1e18f`) `
Scanner used: `MAD`

## PokeAlarm Setup:

Your config file: 
Your filters file: 
Your alarms file:

**Comment by cheveuxroux69** [comment]
alarms file:
```
"alarms-raid-special": {
    "active": true,
    "startup_message": false,
    "type": "discord",
    "webhook_url": "https://discordapp.com/api/webhooks/79851030XXXXXXXX/XXXXXXXX",
    "raids": {
      "username": "<gym_name>",
      "title": "L<raid_lvl> <form_or_empty> <mon_name>",
      "url": "<gmaps>",
      "icon_url": "<gym_image>",
      "body": "Until <24h_raid_end_no_secs>"
    }
```

**Comment by LegitDongo** [comment]
I tried both methods and had no problems, what happens exactly when you try to open the link in the `http://maps.google.com/maps?q={lat,lng}` format?

**Comment by cheveuxroux69** [comment]
On my Android device, using the mod above, the map opens:
https://user-images.githubusercontent.com/3187201/151977295-22e22870-8593-4dad-b354-b17dba32a553.mp4

When I use the project (original) code, the map does not open:
https://user-images.githubusercontent.com/3187201/151977300-e5631ae9-7166-4a18-8ce4-9e9a5f267858.mp4

Both methods work using Discord for Windows.

**Comment by LegitDongo** [comment]
I tried both on Android 11 and had no problems is what I meant to say 😄 

Looks like you're using 12; either way, this seems like it is indeed a bug

at the very least, we should change to use the new api method

**Comment by billyjbryant** [comment]
@cheveuxroux69 please test https://github.com/pokealarm/pokealarm/pull/789 to see if this resolves your issues.

**Comment by billyjbryant** [comment]
#789 has been merged which resolves this bug.
