### ISSUE TITLE
Weatherboosted DTS for Raids with RDM

### ISSUE THREAD

**Issue by Gerbrum** [pokealarm/pokealarm#797]
## Description

Currently there is no working solution i am aware of to display if a raid is boosted by the current weather or not.
I tried existing weather DTS with following results:
<weather_id> reports ? 
\<weather\> reports unknown
## Why is this enhancement necessary or useful?

Users could specifically target raids with weather boost.
## How can this enhancement be accomplished?

Probably by RDM handing over the correct data? I am unsure.

**Comment by Pontiky** [comment]
It seems to be a RDM/MAD "issue", not a PokeAlarm issue.
Looking at the webhook sent by RDM, it doesn't contain a weather field for raid events.
MAD does but doesn't fill it. So the result is the same: PokeAlarm can't determine the current weather or if the raid is weather boosted by receiving a raid event.

For those who use MAD, I made a PR from their side to fill the weather field of the webhook. With this one, PA can determine if the raid is boosted when the egg hatches.
https://github.com/Map-A-Droid/MAD/pull/1225.

**Comment by billyjbryant** [comment]
Resolving since this is related to an issue with the 3rd party package not with PA.
