### ISSUE TITLE
PVP Leaderboard Information

### ISSUE THREAD

**Issue by LegitDongo** [pokealarm/pokealarm#830]
## Description
Most people only care about PVP based on it's official ranking according to popular websites

## Why is this enhancement necessary or useful?
Frequently requested

## How can this enhancement be accomplished?
1. Grab rank from popular websites, cache and refresh on command/periodically
1a. Unsure what this will require, might be impossible without scraping
2. Add filters that only show x top spots
3. Add some nice DTS appropriately

**Comment by BoomEX-UK** [comment]
Hello - have you considered that PVPoke is on Github? They have .json files with rankings.

For example, for GBL ranking you can use this folder
https://github.com/pvpoke/pvpoke/tree/master/src/data/rankings/gobattleleague/overall

The number after the file represents the max CP.
