### ISSUE TITLE
Define alarm.json within filter.json

### ISSUE THREAD

**Issue by BoomEX-UK** [pokealarm/pokealarm#833]
## Description
Currently Alarms are set at run time, per manager. I propose defining which alarm.json to use inside the filters.json file.

## Why is this enhancement necessary or useful?
Currently each filter is locked to a single alarm at runtime however each filter.json can use multiple filters conditions. There have been situations where I have not been able to use a single filter.json file as I need a unique webhook (discord) per alarm.

## How can this enhancement be accomplished?
```
{
    "monsters":{
        "enabled":true,
        "defaults":{},
        "filters":{
            "IV90":{
                "min_iv": 90,"max_iv":94.99, "is_missing_info":false,
                "alarm_file":"alarms/iv90.json"
            },
            "IV95":{
                "min_iv": 95, "max_iv":99.99,"is_missing_info":false,
                "alarm_file":"alarms/iv95.json"
            }
        }
    }
}
```

**Comment by LegitDongo** [comment]
Have you had a look at [Rules](https://pa.readthedocs.io/en/dev/configuration/rules.html)?

It might have what you're looking for, you can use multiple filters per alarm, or multiple alarms per filter

If that isn't enough, you can also use [custom DTS](https://pa.readthedocs.io/en/dev/guides/getting-started-guide.html?highlight=custom%20dts#advanced-custom-dts) in your webhook_url field on your alarm; this limits the amount of alarms you need to be more like a "template" than a "1 channel = 1 alarm" kind of thing

If you've checked these out, and it's still not enough, I'd like to know what kind of use-case this would have

**Comment by BoomEX-UK** [comment]
This may be what I'm looking for. Where I have become confused is the following error on run:
`2022-06-14 17:02:56,654 [CRITI][ pokealarm][ webserver] Number of arguments must be either 1 for all managers or equal to Manager Count. Please provided the correct number of arguments.`
For example, I could not have 2 filter files and 5 alarm files.

I think what this does mean, is that I need to be more organised with my managers?

**Comment by LegitDongo** [comment]
Please share your config file (with sensitive information omitted)

As for the error, I think you have to have a file listed for every manager if you specify a list of filters/alarms/rules per manager

for example,
```
managers: 3
filters: [f1.json, f2.json, f3.json]
alarms: [a1.json, a2.json, a3.json]
```

You should be able to list a filter file multiple times here, and `null` if appropriate

**Comment by LegitDongo** [comment]
Generally people will use multiple Rules instead of managers, might be something to consider here

**Comment by BoomEX-UK** [comment]
OK - and am I correct that I also need 3x rules files in your example? As the rules will have to be specific to the filters in each of the 3 files.

**Comment by LegitDongo** [comment]
yes

the exception here is if the filters/alarms are all named the same, then you can reference a singular rules file with `rules: rulesfile.json`

**Comment by BoomEX-UK** [comment]
Thank you, this is a lot more versatile than the managers approach and answers my questions

**Comment by LegitDongo** [comment]
No problem

If you have further questions, feel free to ask on the [Discord server](https://discord.gg/S2BKC7p)

It's a little less formal than GitHub 😄
