### ISSUE TITLE
Rocket leaders/boss stopped working in alarms

### ISSUE THREAD

**Issue by Misterh8er** [pokealarm/pokealarm#841]
## Troubleshooting Checklist
- [x] My scanner install is at the most recent version.
- [x] My PokeAlarm install is at the most recent version.
- [x] I've already checked the [FAQ](https://pa.readthedocs.io/en/dev/getting-started/faq.html) and the [Wiki](https://pa.readthedocs.io/en/dev/) already.

## Problem Description
Stopped receiving rocket leader/boss alarms around a month ago. I still receive grunts.

## Environment
Operating System: Ubuntu 20.04
Python Version: 3.7.13
PokeAlarm Version: 3.8
Scanner used: RDM

## PokeAlarm Setup:
Your config file: https://www.toptal.com/developers/hastebin/cukexetiho.yaml
Your filters file: https://www.toptal.com/developers/hastebin/mazumuguxu.json
Your alarms file:  https://www.toptal.com/developers/hastebin/naberokoju.json

## Log Output
none (happens in Discord alarms)

**Comment by Misterh8er** [comment]
Type_name doesn't populate the boss name anymore. Was told to change it to grunt_name and it is fine now. Image works as well

**Comment by Pontiky** [comment]
> Type_name doesn't populate the boss name anymore. Was told to change it to grunt_name and it is fine now. Image works as well

<type_name> changed with PR https://github.com/pokealarm/pokealarm/pull/842
This PR is to bring back grunt images in the invasion alerts. ^^
